---
- hosts: all
  become: true
  tasks:
   - name: Install Apache HTTP Servers
     yum:
      name: httpd
      state: latest
   - name: start the Apache servers
     service:
      state: started
      enabled: true
...
